# **Student Productivity and Behaviours Project**

## Objectives

* First I found the dataset from Kaggle, please see the link below;
https://www.kaggle.com/datasets/algozee/student-productivity-and-behavior-dataset-20k
I will then perform the initial ETL pipeline as in Load the raw data, start the initial exploration, clean the data by handling missing values, duplicates, outliers. Export the Clean data. Start the Data visualisation process by conducting descrptive statistics such as mean, median etc. I will then use histograms, box plots to show the visualisation of these statistics. I will then analyse the relationships between variables using correlation heatmaps. Next I will create visualisations to back up my business requirements and hypotheses using charts and graphs. In powerBI, I will create interactive dashboards for complex visualisations. I will aslo create filters and storytelling. Finaly I will create a report of my findings and write a conclusion.

## Inputs

* Raw dataset from Kaggle, numpy, pandas, seaborn, matplotlib, plotly, scikit-learn, powerBI

## Outputs

* Write here which files, code or artefacts you generate by the end of the notebook 

## Additional Comments

* If you have any additional comments that don't fit in the previous bullets, please state them here.

---

# Change working directory

* We are assuming you will store the notebooks in a subfolder, therefore when running the notebook in the editor, you will need to change the working directory

We need to change the working directory from its current folder to its parent folder
* We access the current directory with os.getcwd()

In [13]:
import os
current_dir = os.getcwd()
current_dir

'c:\\Users\\leha_\\Documents\\vscode-projects'

We want to make the parent of the current directory the new current directory
* os.path.dirname() gets the parent directory
* os.chir() defines the new current directory

In [14]:
os.chdir(os.path.dirname(current_dir))
print("You set a new current directory")

You set a new current directory

Confirm the new current directory

In [15]:
current_dir = os.getcwd()
current_dir

'c:\\Users\\leha_\\Documents'

# Section 1

Section 1 content

---

In [16]:
# import libraries that are required
import numpy as np  
import pandas as pd
import matplotlib.pyplot as plt
import plotly.express as px
import seaborn as sns
sns.set_style('whitegrid')

# Section 2

Section 2 content

In [7]:
#check what files are in the current directory
print("Current directory:", os.getcwd())

Current directory: c:\Users\leha_\Documents\vscode-projects\Student-Productivity-and-Behaviours-Project

Loading the raw data and once loaded, the initial data exploration will be explored. We start with the head() and tail() methods.

In [6]:
# Load the raw dataset
df = pd.read_csv('RawData/student_productivity_distraction_dataset_20000.csv')
df.head()

,student_id,age,gender,study_hours_per_day,sleep_hours,phone_usage_hours,social_media_hours,youtube_hours,gaming_hours,breaks_per_day,coffee_intake_mg,exercise_minutes,assignments_completed,attendance_percentage,stress_level,focus_score,final_grade,productivity_score
0,1,23,Female,4.35,3.63,3.38,2.73,1.83,5.26,6,347,111,2,57.21,10,57,81.87,33.78
1,2,20,Male,6.14,6.58,5.48,1.51,3.13,1.73,13,403,28,10,91.27,10,49,60.90,48.99
2,3,29,Female,4.98,3.26,4.83,3.63,0.18,4.71,1,419,102,8,63.14,2,38,86.22,36.60
3,4,27,Female,3.19,4.58,10.06,3.95,5.75,2.52,9,178,28,18,40.51,6,50,71.77,19.87
4,5,24,Male,7.67,6.21,3.02,1.59,5.46,5.65,8,436,105,7,45.53,6,41,90.13,52.90

The above shows the first 5 rows of the dataset.

---

In [17]:
# Using tail() to check the last few rows of the dataset
df.tail()

,student_id,age,gender,study_hours_per_day,sleep_hours,phone_usage_hours,social_media_hours,youtube_hours,gaming_hours,breaks_per_day,coffee_intake_mg,exercise_minutes,assignments_completed,attendance_percentage,stress_level,focus_score,final_grade,productivity_score
19995,19996,26,Female,4.81,7.83,6.86,6.93,2.77,5.68,6,451,0,11,63.69,3,89,82.13,60.43
19996,19997,22,Other,0.83,4.49,6.76,3.79,2.95,1.38,1,375,13,4,74.06,10,56,87.12,17.84
19997,19998,25,Male,9.36,4.33,2.94,6.98,0.35,1.42,4,413,1,11,73.18,9,69,81.58,65.56
19998,19999,22,Female,0.74,4.44,3.15,5.99,3.11,5.01,7,319,1,6,77.02,5,53,53.04,28.06
19999,20000,19,Female,3.64,6.35,8.68,0.11,5.19,1.28,8,50,70,9,40.08,9,65,72.70,30.37

The above two methods are important because it shows a quick snapshot of the beginning and end of a dataset.

In [8]:
# using info() to check the data types of the columns and if there are any missing values
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 20000 entries, 0 to 19999
Data columns (total 18 columns):
 #   Column                 Non-Null Count  Dtype
---  ------                 --------------  -----
 0   student_id             20000 non-null  int64
 1   age                    20000 non-null  int64
 2   gender                 20000 non-null  object
 3   study_hours_per_day    20000 non-null  float64
 4   sleep_hours            20000 non-null  float64
 5   phone_usage_hours      20000 non-null  float64
 6   social_media_hours     20000 non-null  float64
 7   youtube_hours          20000 non-null  float64
 8   gaming_hours           20000 non-null  float64
 9   breaks_per_day         20000 non-null  int64
 10  coffee_intake_mg       20000 non-null  int64
 11  exercise_minutes       20000 non-null  int64
 12  assignments_completed  20000 non-null  int64
 13  attendance_percentage  20000 non-null  float64
 14  stress_level           20000 non-null  int64
 15  focus_score            20000 non-null  int64
 16  final_grade            20000 non-null  float64
 17  productivity_score     20000 non-null  float64
dtypes: float64(9), int64(8), object(1)
memory usage: 2.7+ MB

By using the info() method, I can gather more information about the data. 
The data has 20,000 rows and 18 columns. There is one categorical column which is gender. It also shows the non-null values. I can confirm that there are no non-null values which means that there are no missing values in my dataset.

In [18]:
# using shape to check the number of rows and columns in the dataset
df.shape

(20000, 18)

The above method verifies the rows and columns that we also saw through via the info() method.

In [19]:
# using data types to check the data types of the columns
df.dtypes

student_id                 int64
age                        int64
gender                    object
study_hours_per_day      float64
sleep_hours              float64
phone_usage_hours        float64
social_media_hours       float64
youtube_hours            float64
gaming_hours             float64
breaks_per_day             int64
coffee_intake_mg           int64
exercise_minutes           int64
assignments_completed      int64
attendance_percentage    float64
stress_level               int64
focus_score                int64
final_grade              float64
productivity_score       float64
dtype: object

In [25]:
# show unique values in the gender column
df['gender'].unique()

array(['Female', 'Male', 'Other'], dtype=object)

In [26]:
# show the count of each unique value in the gender column
df['gender'].value_counts()

gender
Female    9640
Male      9582
Other      778
Name: count, dtype: int64

Using the methods above shows a little more depth analysis for the categorical variable in my dataset.

In [27]:
# using describe() to get a statistical summary of the dataset
df.describe()

,student_id,age,study_hours_per_day,sleep_hours,phone_usage_hours,social_media_hours,youtube_hours,gaming_hours,breaks_per_day,coffee_intake_mg,exercise_minutes,assignments_completed,attendance_percentage,stress_level,focus_score,final_grade,productivity_score
count,20000.000000,20000.00000,20000.000000,20000.000000,20000.000000,20000.000000,20000.000000,20000.000000,20000.000000,20000.000000,20000.000000,20000.000000,20000.000000,20000.000000,20000.000000,20000.000000,20000.000000
mean,10000.500000,23.00745,5.254562,6.517799,6.250479,4.003655,2.990177,2.988339,7.542400,249.654550,59.648050,9.494100,69.947435,5.478750,64.444350,70.266409,50.180419
std,5773.647028,3.75489,2.742876,2.029784,3.313082,2.305154,1.729815,1.732803,4.016231,143.711231,34.611751,5.801469,17.397431,2.866943,20.176114,17.282277,16.086666
min,1.000000,17.00000,0.500000,3.000000,0.500000,0.000000,0.000000,0.000000,1.000000,0.000000,0.000000,0.000000,40.000000,1.000000,30.000000,40.000000,0.000000
25%,5000.750000,20.00000,2.900000,4.770000,3.380000,2.000000,1.487500,1.490000,4.000000,125.000000,30.000000,4.000000,54.810000,3.000000,47.000000,55.460000,38.700000
50%,10000.500000,23.00000,5.250000,6.510000,6.240000,4.010000,2.980000,2.970000,8.000000,249.000000,60.000000,9.000000,69.985000,5.000000,65.000000,70.315000,50.235000
75%,15000.250000,26.00000,7.640000,8.310000,9.102500,5.970000,4.480000,4.490000,11.000000,373.000000,90.000000,15.000000,85.050000,8.000000,82.000000,85.340000,61.782500
max,20000.000000,29.00000,10.000000,10.000000,12.000000,8.000000,6.000000,6.000000,14.000000,499.000000,119.000000,19.000000,100.000000,10.000000,99.000000,99.990000,100.000000

The describe() summarises the central tendency, dispersion and shape of a dataset. This is useful as for numerical data shows the count, mean, std, min, max, lower, 50 and upper percentiles. This can help identify outliers.

In [ ]:
# using corr() to check the correlation between the numerical columns only in the dataset
df.select_dtypes(include=np.number).corr()

,student_id,age,study_hours_per_day,sleep_hours,phone_usage_hours,social_media_hours,youtube_hours,gaming_hours,breaks_per_day,coffee_intake_mg,exercise_minutes,assignments_completed,attendance_percentage,stress_level,focus_score,final_grade,productivity_score
student_id,1.000000,-0.004398,0.010596,-0.012768,-0.001470,0.000120,-0.004159,0.005024,0.003951,0.004558,-0.002843,0.003091,0.021324,0.006859,0.015330,0.007043,0.012579
age,-0.004398,1.000000,-0.005029,0.010650,0.009090,0.003258,0.013934,0.001777,-0.006727,0.006629,0.001646,-0.003458,-0.006531,-0.002612,-0.004130,-0.000857,-0.005423
study_hours_per_day,0.010596,-0.005029,1.000000,0.001670,0.011539,0.004888,-0.002238,-0.002104,-0.010371,0.004788,0.004380,0.005643,-0.008083,0.001781,0.004536,-0.012208,0.732777
sleep_hours,-0.012768,0.010650,0.001670,1.000000,0.000016,-0.005939,0.004920,-0.003666,-0.000677,0.000882,0.006526,0.000944,0.003433,0.000020,-0.003241,0.010543,0.340902
phone_usage_hours,-0.001470,0.009090,0.011539,0.000016,1.000000,0.004030,0.004108,-0.007497,-0.005431,-0.000064,-0.003186,0.006213,-0.002986,0.006138,-0.000206,-0.012136,-0.326650
social_media_hours,0.000120,0.003258,0.004888,-0.005939,0.004030,1.000000,-0.005172,0.006406,-0.004077,-0.003837,-0.006226,0.003418,0.009388,0.000355,-0.001285,-0.000117,0.001285
youtube_hours,-0.004159,0.013934,-0.002238,0.004920,0.004108,-0.005172,1.000000,0.005033,-0.012604,0.006495,0.002128,0.011149,0.005766,0.007351,0.003745,0.001579,-0.000224
gaming_hours,0.005024,0.001777,-0.002104,-0.003666,-0.007497,0.006406,0.005033,1.000000,0.005545,-0.010977,-0.000823,0.000179,0.010962,0.001791,-0.001462,0.002544,0.000685
breaks_per_day,0.003951,-0.006727,-0.010371,-0.000677,-0.005431,-0.004077,-0.012604,0.005545,1.000000,-0.000057,-0.015312,0.010554,0.003253,0.002395,0.000269,-0.003690,-0.005836
coffee_intake_mg,0.004558,0.006629,0.004788,0.000882,-0.000064,-0.003837,0.006495,-0.010977,-0.000057,1.000000,0.011384,0.007968,0.003035,-0.008850,0.010121,0.015326,0.010190
exercise_minutes,-0.002843,0.001646,0.004380,0.006526,-0.003186,-0.006226,0.002128,-0.000823,-0.015312,0.011384,1.000000,-0.003826,0.004321,0.009474,-0.006284,-0.002677,0.002892
assignments_completed,0.003091,-0.003458,0.005643,0.000944,0.006213,0.003418,0.011149,0.000179,0.010554,0.007968,-0.003826,1.000000,0.011806,0.016411,-0.007557,0.003894,-0.001757
attendance_percentage,0.021324,-0.006531,-0.008083,0.003433,-0.002986,0.009388,0.005766,0.010962,0.003253,0.003035,0.004321,0.011806,1.000000,-0.005931,0.009111,-0.005270,0.176107
stress_level,0.006859,-0.002612,0.001781,0.000020,0.006138,0.000355,0.007351,0.001791,0.002395,-0.008850,0.009474,0.016411,-0.005931,1.000000,-0.007501,-0.012216,-0.197128
focus_score,0.015330,-0.004130,0.004536,-0.003241,-0.000206,-0.001285,0.003745,-0.001462,0.000269,0.010121,-0.006284,-0.007557,0.009111,-0.007501,1.000000,0.004630,0.411366
final_grade,0.007043,-0.000857,-0.012208,0.010543,-0.012136,-0.000117,0.001579,0.002544,-0.003690,0.015326,-0.002677,0.003894,-0.005270,-0.012216,0.004630,1.000000,0.001954
productivity_score,0.012579,-0.005423,0.732777,0.340902,-0.326650,0.001285,-0.000224,0.000685,-0.005836,0.010190,0.002892,-0.001757,0.176107,-0.197128,0.411366,0.001954,1.000000

 I used the .select_dtypes to include the the numerical data only.

In [35]:
# using spearman method to check the correlation between the numerical columns only in the dataset
df.select_dtypes(include=np.number).corr(method='spearman')

,student_id,age,study_hours_per_day,sleep_hours,phone_usage_hours,social_media_hours,youtube_hours,gaming_hours,breaks_per_day,coffee_intake_mg,exercise_minutes,assignments_completed,attendance_percentage,stress_level,focus_score,final_grade,productivity_score
student_id,1.000000,-0.004377,0.010559,-0.012584,-0.001476,0.000115,-0.004167,0.005012,0.003986,0.004531,-0.002895,0.003066,0.021327,0.006874,0.015332,0.007078,0.013760
age,-0.004377,1.000000,-0.005136,0.010652,0.009048,0.003237,0.013861,0.001748,-0.006719,0.006667,0.001571,-0.003457,-0.006523,-0.002637,-0.004145,-0.000956,-0.005882
study_hours_per_day,0.010559,-0.005136,1.000000,0.001610,0.011429,0.004812,-0.002137,-0.002150,-0.010328,0.004776,0.004311,0.005564,-0.008110,0.001791,0.004564,-0.012243,0.739153
sleep_hours,-0.012584,0.010652,0.001610,1.000000,0.000051,-0.005912,0.004886,-0.003648,-0.000687,0.000835,0.006575,0.000937,0.003449,-0.000092,-0.003265,0.010670,0.327574
phone_usage_hours,-0.001476,0.009048,0.011429,0.000051,1.000000,0.003943,0.004073,-0.007447,-0.005457,-0.000035,-0.003192,0.006335,-0.003031,0.006158,-0.000209,-0.012194,-0.313751
social_media_hours,0.000115,0.003237,0.004812,-0.005912,0.003943,1.000000,-0.005305,0.006383,-0.004099,-0.003806,-0.006269,0.003350,0.009362,0.000306,-0.001301,-0.000134,0.001550
youtube_hours,-0.004167,0.013861,-0.002137,0.004886,0.004073,-0.005305,1.000000,0.004994,-0.012612,0.006526,0.002142,0.011201,0.005830,0.007397,0.003648,0.001544,-0.001529
gaming_hours,0.005012,0.001748,-0.002150,-0.003648,-0.007447,0.006383,0.004994,1.000000,0.005440,-0.010993,-0.000746,0.000203,0.010960,0.001709,-0.001407,0.002509,0.000744
breaks_per_day,0.003986,-0.006719,-0.010328,-0.000687,-0.005457,-0.004099,-0.012612,0.005440,1.000000,-0.000089,-0.015426,0.010567,0.003180,0.002386,0.000316,-0.003714,-0.004525
coffee_intake_mg,0.004531,0.006667,0.004776,0.000835,-0.000035,-0.003806,0.006526,-0.010993,-0.000089,1.000000,0.011278,0.007958,0.003080,-0.008846,0.010074,0.015353,0.008780
exercise_minutes,-0.002895,0.001571,0.004311,0.006575,-0.003192,-0.006269,0.002142,-0.000746,-0.015426,0.011278,1.000000,-0.003835,0.004245,0.009486,-0.006221,-0.002522,0.002925
assignments_completed,0.003066,-0.003457,0.005564,0.000937,0.006335,0.003350,0.011201,0.000203,0.010567,0.007958,-0.003835,1.000000,0.011736,0.016436,-0.007530,0.003847,-0.001897
attendance_percentage,0.021327,-0.006523,-0.008110,0.003449,-0.003031,0.009362,0.005830,0.010960,0.003180,0.003080,0.004245,0.011736,1.000000,-0.005931,0.009051,-0.005282,0.168387
stress_level,0.006874,-0.002637,0.001791,-0.000092,0.006158,0.000306,0.007397,0.001709,0.002386,-0.008846,0.009486,0.016436,-0.005931,1.000000,-0.007455,-0.012043,-0.186383
focus_score,0.015332,-0.004145,0.004564,-0.003265,-0.000209,-0.001301,0.003648,-0.001407,0.000316,0.010074,-0.006221,-0.007530,0.009051,-0.007455,1.000000,0.004609,0.397212
final_grade,0.007078,-0.000956,-0.012243,0.010670,-0.012194,-0.000134,0.001544,0.002509,-0.003714,0.015353,-0.002522,0.003847,-0.005282,-0.012043,0.004609,1.000000,0.002647
productivity_score,0.013760,-0.005882,0.739153,0.327574,-0.313751,0.001550,-0.001529,0.000744,-0.004525,0.008780,0.002925,-0.001897,0.168387,-0.186383,0.397212,0.002647,1.000000

Using the 'spearman' method, this is to assess the monotonic relationships in numerical variables.

Moving on to the cleaning section. 
Missing - Confirmed already that there are no missing values
Duplicates
Outliers

---

# Push files to Repo

* In cases where you don't need to push files to Repo, you may replace this section with "Conclusions and Next Steps" and state your conclusions and next steps.

In [ ]:
import os
try:
  # create your folder here
  # os.makedirs(name='')
except Exception as e:
  print(e)